#!/bin/bash

# List of packages to uninstall from Samsung (com. before the package name)
declare -a samsung_bloatware=(
    "com.samsung.android.bixby.wakeup"
    "com.samsung.android.app.spage"
    "com.samsung.android.app.routines"
    "com.samsung.android.bixby.service"
    "com.samsung.android.visionintelligence"
    "com.samsung.android.bixby.agent"
    "com.samsung.android.bixby.agent.dummy"
    "com.samsung.android.bixbyvision.framework"
    "com.dsi.ant.sample.acquirechannels"
    "com.dsi.ant.service.socket"
    "com.dsi.ant.server"
    "com.dsi.ant.plugins.antplus"
    "com.samsung.android.messaging"
    "com.sec.android.easyonehand"
    "com.samsung.android.drivelink.stub"
    "com.sec.android.widgetapp.samsungapps"
    "com.sec.android.app.sbrowser"
    "com.samsung.android.mateagent"
    "com.sec.android.easyMover.Agent"
    "com.samsung.android.app.watchmanagerstub"
    "com.sec.android.daemonapp"
    "com.samsung.android.app.social"
    "com.samsung.ecomm.global"
    "com.sec.android.app.voicenote"
    "com.samsung.android.oneconnect"
    "com.samsung.android.voc"
    "com.sec.android.app.popupcalculator"
    "com.sec.android.splitsound"
    "com.mobeam.barcodeService"
    "com.samsung.android.app.dressroom"
    "com.samsung.android.scloud"
    "com.samsung.android.sdk.handwriting"
    "com.samsung.android.sdk.professionalaudio.utility.jammonitor"
    "com.samsung.android.universalswitch"
    "com.samsung.android.visioncloudagent"
    "com.samsung.android.widgetapp.yahooedge.finance"
    "com.samsung.android.widgetapp.yahooedge.sport"
    "com.samsung.app.highlightplayer"
    "com.samsung.safetyinformation"
    "com.samsung.storyservice"
    "com.samsung.android.service.aircommand"
    "com.samsung.android.app.aodservice"
    "com.sec.android.app.dexonpc"
    "com.samsung.android.ardrawing"
    "com.samsung.android.svoiceime"
    "com.samsung.android.beaconmanager"
    "com.samsung.android.email.provider"
    "com.wsomacp"
    "com.samsung.android.samsungpassautofill"
    "com.samsung.android.authfw"
    "com.samsung.android.samsungpass"
    "com.samsung.android.spay"
    "com.samsung.android.spayfw"
    "com.android.bips"
    "com.google.android.printservice.recommendation"
    "com.android.printspooler"
    "com.boxer.app"
    "com.samsung.android.wellbeing"
    "com.samsung.android.da.daagent"
    "com.samsung.android.service.livedrawing"
    "com.samsung.android.aremoji"
    "com.sec.android.mimage.avatarstickers"
    "com.samsung.android.emojiupdater"
    "com.samsung.android.hmt.vrsvc"
    "com.samsung.android.app.vrsetupwizardstub"
    "com.samsung.android.hmt.vrshell"
    "com.google.vr.vrcore"
    "com.samsung.android.kidsinstaller"
    "com.samsung.android.app.camera.sticker.facearavatar.preload"
    "com.sec.android.app.kidshome"
    "com.samsung.android.game.gamehome"
    "com.enhance.gameservice"
    "com.samsung.android.game.gametools"
    "com.samsung.android.game.gos"
    "com.samsung.android.gametuner.thin"
    "com.samsung.android.app.ledbackcover"
    "com.sec.android.cover.ledcover"
    "com.sec.android.desktopmode.uiservice"
    "com.samsung.desktopsystemui"
    "com.sec.android.app.desktoplauncher"
    "com.vcast.mediamanager"
    "com.samsung.vmmhux"
    "com.vzw.hss.myverizon"
    "com.asurion.android.verizon.vms"
    "com.motricity.verizon.ssodownloadable"
    "com.vzw.hs.android.modlite"
    "com.samsung.vvm"
    "com.vznavigator"
    "com.att.dh"
    "com.att.dtv.shaderemote"
    "com.att.tv"
    "com.samsung.attvvm"
    "com.att.myWireless"
    "com.asurion.android.protech.att"
    "com.att.android.attsmartwifi"
    "com.android.bookmarkprovider"
    "com.android.browser"
    "com.android.calendar"
    "com.android.cellbroadcastreceiver"
    "com.android.cellbroadcastreceiver.overlay.common"
    "com.android.chrome"
    "com.sec.android.app.chromecustomizations"
    "com.android.deskclock"
    "com.android.dreams.basic"
    "com.android.dreams.phototable"
    "com.android.egg"
    "com.android.emergency"
    "com.android.hotwordenrollment.okgoogle"
    "com.android.mms"
    "com.android.mms.service"
    "com.android.printspooler"
    "com.android.statementservice"
    "com.android.stk"
    "com.android.wallpaper.livepicker"
    "com.android.wallpaperbackup"
    "com.android.wallpapercropper"
    "com.android.providers.downloads.ui"
    "com.android.providers.partnerbookmarks"
    "com.android.sharedstoragebackup"
    "com.android.vpndialogs"
    "com.facebook.katana"
    "com.facebook.system"
    "com.facebook.appmanager"
    "com.facebook.services"
    "com.google.android.apps.docs"
    "com.google.android.apps.maps"
    "com.google.android.apps.photos"
    "com.google.android.apps.tachyon"
    "com.google.android.apps.wellbeing"
    "com.google.android.feedback"
    "com.google.android.gm"
    "com.google.android.googlequicksearchbox"
    "com.google.android.inputmethod.latin"
    "com.google.android.marvin.talkback"
    "com.google.android.music"
    "com.google.android.printservice.recommendation"
    "com.google.android.syncadapters.calendar"
    "com.google.android.tts"
    "com.google.android.videos"
    "com.google.android.youtube"
    "com.google.ar.lens"
    "com.cnn.mobile.android.phone.edgepanel"
    "com.samsung.android.service.peoplestripe"
    "com.samsung.android.app.sbrowseredge"
    "com.samsung.android.app.appsedge"
    "com.gocro.smartnews.android"
    "com.synchronoss.dcs.att.r2g"
    "com.wavemarket.waplauncher"
    "com.pandora.android"
    "com.sec.penup"
    "com.linkedin.android"
    "com.hunge.app"
    "com.greatbigstory.greatbigstory"
    "com.android.documentsui"
    "com.drivemode"
    "com.samsung.android.app.contacts"
    "com.samsung.android.calendar"
    "com.cnn.mobile.android.phone"
    "com.bleacherreport.android.teamstream"
    "com.aetherpal.device"
    "com.google.android.dialer"
    "com.wb.goog.got.conquest"
    "com.wb.goog.dcuniverse"
    "com.innogames.foeandroid"
    "com.playstudios.popslots"
    "com.gsn.android.tripeaks"
    "com.foxnextgames.m3"
    "com.audible.application"
    "com.microsoft.skydrive"
)

# Function to uninstall bloatware
remove_bloatware() {
    for pkg in "${samsung_bloatware[@]}"; do
        echo -n "You want to uninstall, disable and force stop the package: $pkg (y/n)? "
        read -r choice
        if [[ "$choice" == "y" || "$choice" == "Y" ]]; then
            # Force stop
            echo "Forcing packet stop: $pkg..."
            adb shell am force-stop "$pkg"
            if [[ $? -eq 0 ]]; then
                echo "Success: $pkg was stopped."
            else
                echo "Error: Unable to stop $pkg."
            fi

            # Disable the application
            echo "Disabling the package: $pkg..."
            adb shell pm disable-user --user 0 "$pkg"
            if [[ $? -eq 0 ]]; then
                echo "Success: $pkg has been deactivated."
            else
                echo "Error: Unable to deactivate $pkg."
            fi

            # Uninstall the application
            echo "Uninstalling the package: $pkg..."
            adb shell pm uninstall --user 0 "$pkg"
            if [[ $? -eq 0 ]]; then
                echo "Success: $pkg has been uninstalled."
            else
                echo "Erro: Unable to uninstall $pkg."
            fi
        else
            echo "Skipping the package: $pkg."
        fi
    done
}

# Start bloatware removal
echo "Starting bloatware removal."
remove_bloatware
echo "Process completed."
